name: Deploy to Skynet

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build webapp
        run: npm run build

      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          try-files: /index.html
          portal-url: https://skynetfree.net
          skynet-api-key: ${{ secrets.SKYNET_API_KEY }}
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}